(* generated by dune *)

(** @canonical Prettym.Enclosure *)
module Enclosure = Prettym__Enclosure

(** @canonical Prettym.Fancy *)
module Fancy = Prettym__Fancy

(** @canonical Prettym.Pretty *)
module Pretty = Prettym__Pretty
