(* generated by dune *)

(** @canonical Mrmime.Address *)
module Address = Mrmime__Address

(** @canonical Mrmime.B64 *)
module B64 = Mrmime__B64

(** @canonical Mrmime.Content_encoding *)
module Content_encoding = Mrmime__Content_encoding

(** @canonical Mrmime.Content_type *)
module Content_type = Mrmime__Content_type

(** @canonical Mrmime.Date *)
module Date = Mrmime__Date

(** @canonical Mrmime.Encoded_word *)
module Encoded_word = Mrmime__Encoded_word

(** @canonical Mrmime.Field *)
module Field = Mrmime__Field

(** @canonical Mrmime.Field_name *)
module Field_name = Mrmime__Field_name

(** @canonical Mrmime.Group *)
module Group = Mrmime__Group

(** @canonical Mrmime.Hd *)
module Hd = Mrmime__Hd

(** @canonical Mrmime.Header *)
module Header = Mrmime__Header

(** @canonical Mrmime.Iana *)
module Iana = Mrmime__Iana

(** @canonical Mrmime.Location *)
module Location = Mrmime__Location

(** @canonical Mrmime.Mail *)
module Mail = Mrmime__Mail

(** @canonical Mrmime.Mailbox *)
module Mailbox = Mrmime__Mailbox

(** @canonical Mrmime.MessageID *)
module MessageID = Mrmime__MessageID

(** @canonical Mrmime.Mt *)
module Mt = Mrmime__Mt

(** @canonical Mrmime.Option *)
module Option = Mrmime__Option

(** @canonical Mrmime.Peano *)
module Peano = Mrmime__Peano

(** @canonical Mrmime.Quoted_printable *)
module Quoted_printable = Mrmime__Quoted_printable

(** @canonical Mrmime.Rfc2046 *)
module Rfc2046 = Mrmime__Rfc2046

(** @canonical Mrmime.Unstructured *)
module Unstructured = Mrmime__Unstructured
