# -*- mode: org; coding: utf-8 -*-
#+TITLE: Prelude: My OCaml Standard Library Additions and Renamings
#+AUTHOR: Keith Waclena
#+EMAIL:
#+OPTIONS: toc:nil num:nil tags:nil email:off ^:{}
* Introduction
Prelude is my personal OCaml library and is a prerequisite for all my
other code.  For details, see [[https://www2.lib.uchicago.edu/keith/software/prelude/Prelude.html][the documentation]].
* Prerequisites
** OS Prerequisites
[[https://opam.ocaml.org/doc/Install.html][Install Opam]], the OCaml package manager, from your OS package system.

After installation, initialize Opam:
: opam init

Optionally install [[https://www.gnu.org/software/make][GNU make]] if you're used to =make=.
** An OCaml Compiler
Install the OCaml compiler (called a /switch/) via Opam.  The latest
version of OCaml known to work is 4.12.1:
: opam switch create 4.12.1
This is an install from source, so be patient: it may take a minute.

Don't forget to run the advertised =eval $(opam env)= to update your
=PATH= accordingly.
** Build System
Now install Prelude's prerequisites via Opam.  Prelude uses the =dune=
build system:
: opam install dune
* Install Prelude
Now you can compile and install Prelude:
: dune build @install
If you've installed GNU make, you can instead run:
: make install
* Generating Documentation
If you want to generate the documentation (no different than at the
URL above), you'll need to install the documentation generator:
: opam install odoc
