(* generated by dune *)

(** @canonical Uuuu.ISO_8859_1 *)
module ISO_8859_1 = Uuuu__ISO_8859_1

(** @canonical Uuuu.ISO_8859_10 *)
module ISO_8859_10 = Uuuu__ISO_8859_10

(** @canonical Uuuu.ISO_8859_11 *)
module ISO_8859_11 = Uuuu__ISO_8859_11

(** @canonical Uuuu.ISO_8859_13 *)
module ISO_8859_13 = Uuuu__ISO_8859_13

(** @canonical Uuuu.ISO_8859_14 *)
module ISO_8859_14 = Uuuu__ISO_8859_14

(** @canonical Uuuu.ISO_8859_15 *)
module ISO_8859_15 = Uuuu__ISO_8859_15

(** @canonical Uuuu.ISO_8859_16 *)
module ISO_8859_16 = Uuuu__ISO_8859_16

(** @canonical Uuuu.ISO_8859_2 *)
module ISO_8859_2 = Uuuu__ISO_8859_2

(** @canonical Uuuu.ISO_8859_3 *)
module ISO_8859_3 = Uuuu__ISO_8859_3

(** @canonical Uuuu.ISO_8859_4 *)
module ISO_8859_4 = Uuuu__ISO_8859_4

(** @canonical Uuuu.ISO_8859_5 *)
module ISO_8859_5 = Uuuu__ISO_8859_5

(** @canonical Uuuu.ISO_8859_6 *)
module ISO_8859_6 = Uuuu__ISO_8859_6

(** @canonical Uuuu.ISO_8859_7 *)
module ISO_8859_7 = Uuuu__ISO_8859_7

(** @canonical Uuuu.ISO_8859_8 *)
module ISO_8859_8 = Uuuu__ISO_8859_8

(** @canonical Uuuu.ISO_8859_9 *)
module ISO_8859_9 = Uuuu__ISO_8859_9
