(************************************************************
 * WARNING!
 *
 * This file is generated by ocamlrpcgen from the source file
 * rpc_auth_gssapi.x
 *
 ************************************************************)

(* Type definitions *)

type rpc_gss_proc_enum_t = 
     Netnumber.int4
and rpc_gss_proc_t = 
     [ 
     | `rpcsec_gss_data 
     | `rpcsec_gss_init 
     | `rpcsec_gss_continue_init 
     | `rpcsec_gss_destroy 
     ]
and rpc_gss_service_enum_t = 
     Netnumber.int4
and rpc_gss_service_t = 
     [ | `rpc_gss_svc_none | `rpc_gss_svc_integrity | `rpc_gss_svc_privacy ]
and rpc_gss_cred_t = 
     [ | `_1 of (_t0) ]
and rpc_gss_init_arg = 
     { 
       mutable gss_token : string;
     }
and rpc_gss_init_res = 
     { 
       mutable res_handle : string;
       mutable res_major : Netnumber.uint4;
       mutable res_minor : Netnumber.uint4;
       mutable res_seq_window : Netnumber.uint4;
       mutable res_token : string;
     }
and rpc_gss_integ_data = 
     { 
       mutable databody_integ : Netxdr_mstring.mstring;
       mutable checksum : string;
     }
and rpc_gss_priv_data = 
     { 
       mutable databody_priv : Netxdr_mstring.mstring;
     }
and _t0 = 
     { 
       mutable gss_proc : rpc_gss_proc_t;
       mutable seq_num : Netnumber.uint4;
       mutable service : rpc_gss_service_t;
       mutable handle : string;
     }
;;

(* Constant definitions *)

val rpcsec_gss_data : Netnumber.int4;;
val rpcsec_gss_init : Netnumber.int4;;
val rpcsec_gss_continue_init : Netnumber.int4;;
val rpcsec_gss_destroy : Netnumber.int4;;
val rpc_gss_svc_none : Netnumber.int4;;
val rpc_gss_svc_integrity : Netnumber.int4;;
val rpc_gss_svc_privacy : Netnumber.int4;;
val gss_s_complete : Netnumber.uint4;;
val gss_s_continue_needed : Netnumber.uint4;;
val zero : Netnumber.uint4;;
val maxseq : Netnumber.uint4;;

(* Conversion functions *)

val _to_rpc_gss_proc_enum_t : Netxdr.xdr_value -> rpc_gss_proc_enum_t;;
val _of_rpc_gss_proc_enum_t : rpc_gss_proc_enum_t -> Netxdr.xdr_value;;
val _xof_rpc_gss_proc_enum_t : Netxdr.ctx -> rpc_gss_proc_enum_t -> Netxdr.xdr_value;;
val _to_rpc_gss_proc_t : Netxdr.xdr_value -> rpc_gss_proc_t;;
val _of_rpc_gss_proc_t : rpc_gss_proc_t -> Netxdr.xdr_value;;
val _xof_rpc_gss_proc_t : Netxdr.ctx -> rpc_gss_proc_t -> Netxdr.xdr_value;;
val _to_rpc_gss_service_enum_t : Netxdr.xdr_value -> rpc_gss_service_enum_t;;
val _of_rpc_gss_service_enum_t : rpc_gss_service_enum_t -> Netxdr.xdr_value;;
val _xof_rpc_gss_service_enum_t : Netxdr.ctx -> rpc_gss_service_enum_t -> Netxdr.xdr_value;;
val _to_rpc_gss_service_t : Netxdr.xdr_value -> rpc_gss_service_t;;
val _of_rpc_gss_service_t : rpc_gss_service_t -> Netxdr.xdr_value;;
val _xof_rpc_gss_service_t : Netxdr.ctx -> rpc_gss_service_t -> Netxdr.xdr_value;;
val _to_rpc_gss_cred_t : Netxdr.xdr_value -> rpc_gss_cred_t;;
val _of_rpc_gss_cred_t : rpc_gss_cred_t -> Netxdr.xdr_value;;
val _xof_rpc_gss_cred_t : Netxdr.ctx -> rpc_gss_cred_t -> Netxdr.xdr_value;;
val _to_rpc_gss_init_arg : Netxdr.xdr_value -> rpc_gss_init_arg;;
val _of_rpc_gss_init_arg : rpc_gss_init_arg -> Netxdr.xdr_value;;
val _xof_rpc_gss_init_arg : Netxdr.ctx -> rpc_gss_init_arg -> Netxdr.xdr_value;;
val _to_rpc_gss_init_res : Netxdr.xdr_value -> rpc_gss_init_res;;
val _of_rpc_gss_init_res : rpc_gss_init_res -> Netxdr.xdr_value;;
val _xof_rpc_gss_init_res : Netxdr.ctx -> rpc_gss_init_res -> Netxdr.xdr_value;;
val _to_rpc_gss_integ_data : Netxdr.xdr_value -> rpc_gss_integ_data;;
val _of_rpc_gss_integ_data : rpc_gss_integ_data -> Netxdr.xdr_value;;
val _xof_rpc_gss_integ_data : Netxdr.ctx -> rpc_gss_integ_data -> Netxdr.xdr_value;;
val _to_rpc_gss_priv_data : Netxdr.xdr_value -> rpc_gss_priv_data;;
val _of_rpc_gss_priv_data : rpc_gss_priv_data -> Netxdr.xdr_value;;
val _xof_rpc_gss_priv_data : Netxdr.ctx -> rpc_gss_priv_data -> Netxdr.xdr_value;;

(* XDR definitions *)

val xdrt_rpc_gss_proc_enum_t : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_proc_t : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_service_enum_t : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_service_t : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_cred_t : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_init_arg : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_init_res : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_integ_data : Netxdr.xdr_type_term;;
val xdrt_rpc_gss_priv_data : Netxdr.xdr_type_term;;

(* Program definitions *)


