(************************************************************
 * WARNING!
 *
 * This file is generated by ocamlrpcgen from the source file
 * rpc_portmapper.x
 *
 ************************************************************)

(* Type definitions *)

type mapping = 
     { 
       mutable prog : Netnumber.uint4;
       mutable vers : Netnumber.uint4;
       mutable prot : int;
       mutable port : int;
     }
and pmaplist = 
     { 
       mutable map : mapping;
       mutable next : pmaplist option;
     }
and pmaplist_p = 
     pmaplist option
and call_args = 
     { 
       mutable call_prog : Netnumber.uint4;
       mutable call_vers : Netnumber.uint4;
       mutable call_proc : Netnumber.uint4;
       mutable call_args : string;
     }
and call_result = 
     { 
       mutable call_port : int;
       mutable call_res : string;
     }
and uaddr = 
     string
and rpcb = 
     { 
       mutable r_prog : Netnumber.uint4;
       mutable r_vers : Netnumber.uint4;
       mutable r_netid : string;
       mutable r_addr : uaddr;
       mutable r_owner : string;
     }
and rp__list = 
     { 
       mutable rpcb_map : rpcb;
       mutable rpcb_next : rp__list option;
     }
and rpcblist_ptr = 
     rp__list option
and rpcb_rmtcallargs = 
     call_args
and rpcb_rmtcallres = 
     { 
       mutable call_addr : uaddr;
       mutable call_res2 : string;
     }
and rpcb_entry = 
     { 
       mutable r_maddr : string;
       mutable r_nc_netid : string;
       mutable r_nc_semantics : int;
       mutable r_nc_protofmly : string;
       mutable r_nc_proto : string;
     }
and rpcb_entry_list = 
     { 
       mutable rpcb_entry_map : rpcb_entry;
       mutable rpcb_entry_next : rpcb_entry_list option;
     }
and rpcb_entry_list_ptr = 
     rpcb_entry_list option
and rpcbs_addrlist = 
     { 
       mutable al_prog : Netnumber.uint4;
       mutable al_vers : Netnumber.uint4;
       mutable al_success : int32;
       mutable al_failure : int32;
       mutable al_netid : string;
       mutable al_next : rpcbs_addrlist option;
     }
and rpcbs_rmtcalllist = 
     { 
       mutable cl_prog : Netnumber.uint4;
       mutable cl_vers : Netnumber.uint4;
       mutable cl_proc : Netnumber.uint4;
       mutable cl_success : int32;
       mutable cl_failure : int32;
       mutable cl_indirect : int32;
       mutable cl_netid : string;
       mutable cl_next : rpcbs_rmtcalllist option;
     }
and rpcbs_proc = 
     Netnumber.int4 array
and rpcbs_addrlist_ptr = 
     rpcbs_addrlist option
and rpcbs_rmtcalllist_ptr = 
     rpcbs_rmtcalllist option
and rpcb_stat = 
     { 
       mutable info : rpcbs_proc;
       mutable setinfo : int32;
       mutable unsetinfo : int32;
       mutable addrinfo : rpcbs_addrlist_ptr;
       mutable rmtinfo : rpcbs_rmtcalllist_ptr;
     }
and rpcb_stat_byvers = 
     rpcb_stat array
and netbuf = 
     { 
       mutable maxlen : Netnumber.uint4;
       mutable buf : string;
     }
and t_PMAP'V2'pmapproc_null'arg = 
     unit
and t_PMAP'V2'pmapproc_null'res = 
     unit
and t_PMAP'V2'pmapproc_set'arg = 
     mapping
and t_PMAP'V2'pmapproc_set'res = 
     bool
and t_PMAP'V2'pmapproc_unset'arg = 
     mapping
and t_PMAP'V2'pmapproc_unset'res = 
     bool
and t_PMAP'V2'pmapproc_getport'arg = 
     mapping
and t_PMAP'V2'pmapproc_getport'res = 
     int
and t_PMAP'V2'pmapproc_dump'arg = 
     unit
and t_PMAP'V2'pmapproc_dump'res = 
     pmaplist_p
and t_PMAP'V2'pmapproc_callit'arg = 
     call_args
and t_PMAP'V2'pmapproc_callit'res = 
     call_result
and t_PMAP'V3'rpcbproc_null'arg = 
     unit
and t_PMAP'V3'rpcbproc_null'res = 
     unit
and t_PMAP'V3'rpcbproc_set'arg = 
     rpcb
and t_PMAP'V3'rpcbproc_set'res = 
     bool
and t_PMAP'V3'rpcbproc_unset'arg = 
     rpcb
and t_PMAP'V3'rpcbproc_unset'res = 
     bool
and t_PMAP'V3'rpcbproc_getaddr'arg = 
     rpcb
and t_PMAP'V3'rpcbproc_getaddr'res = 
     uaddr
and t_PMAP'V3'rpcbproc_dump'arg = 
     unit
and t_PMAP'V3'rpcbproc_dump'res = 
     rpcblist_ptr
and t_PMAP'V3'rpcbproc_callit'arg = 
     rpcb_rmtcallargs
and t_PMAP'V3'rpcbproc_callit'res = 
     rpcb_rmtcallres
and t_PMAP'V3'rpcbproc_gettime'arg = 
     unit
and t_PMAP'V3'rpcbproc_gettime'res = 
     Netnumber.uint4
and t_PMAP'V3'rpcbproc_uaddr2taddr'arg = 
     uaddr
and t_PMAP'V3'rpcbproc_uaddr2taddr'res = 
     netbuf
and t_PMAP'V3'rpcbproc_taddr2uaddr'arg = 
     netbuf
and t_PMAP'V3'rpcbproc_taddr2uaddr'res = 
     uaddr
and t_PMAP'V4'rpcbproc_null'arg = 
     unit
and t_PMAP'V4'rpcbproc_null'res = 
     unit
and t_PMAP'V4'rpcbproc_set'arg = 
     rpcb
and t_PMAP'V4'rpcbproc_set'res = 
     bool
and t_PMAP'V4'rpcbproc_unset'arg = 
     rpcb
and t_PMAP'V4'rpcbproc_unset'res = 
     bool
and t_PMAP'V4'rpcbproc_getaddr'arg = 
     rpcb
and t_PMAP'V4'rpcbproc_getaddr'res = 
     uaddr
and t_PMAP'V4'rpcbproc_dump'arg = 
     unit
and t_PMAP'V4'rpcbproc_dump'res = 
     rpcblist_ptr
and t_PMAP'V4'rpcbproc_bcast'arg = 
     rpcb_rmtcallargs
and t_PMAP'V4'rpcbproc_bcast'res = 
     rpcb_rmtcallres
and t_PMAP'V4'rpcbproc_gettime'arg = 
     unit
and t_PMAP'V4'rpcbproc_gettime'res = 
     Netnumber.uint4
and t_PMAP'V4'rpcbproc_uaddr2taddr'arg = 
     uaddr
and t_PMAP'V4'rpcbproc_uaddr2taddr'res = 
     netbuf
and t_PMAP'V4'rpcbproc_taddr2uaddr'arg = 
     netbuf
and t_PMAP'V4'rpcbproc_taddr2uaddr'res = 
     uaddr
and t_PMAP'V4'rpcbproc_getversaddr'arg = 
     rpcb
and t_PMAP'V4'rpcbproc_getversaddr'res = 
     uaddr
and t_PMAP'V4'rpcbproc_indirect'arg = 
     rpcb_rmtcallargs
and t_PMAP'V4'rpcbproc_indirect'res = 
     rpcb_rmtcallres
and t_PMAP'V4'rpcbproc_getaddrlist'arg = 
     rpcb
and t_PMAP'V4'rpcbproc_getaddrlist'res = 
     rpcb_entry_list_ptr
and t_PMAP'V4'rpcbproc_getstat'arg = 
     unit
and t_PMAP'V4'rpcbproc_getstat'res = 
     rpcb_stat_byvers
;;

(* Constant definitions *)

val pmap_port : Netnumber.uint4;;
val ipproto_tcp : Netnumber.uint4;;
val ipproto_udp : Netnumber.uint4;;
val rpcb_port : Netnumber.uint4;;
val rpcbstat_highproc : Netnumber.uint4;;
val rpcbvers_stat : Netnumber.uint4;;
val rpcbvers_4_stat : Netnumber.uint4;;
val rpcbvers_3_stat : Netnumber.uint4;;
val rpcbvers_2_stat : Netnumber.uint4;;

(* Conversion functions *)

val _to_mapping : Netxdr.xdr_value -> mapping;;
val _of_mapping : mapping -> Netxdr.xdr_value;;
val _xof_mapping : Netxdr.ctx -> mapping -> Netxdr.xdr_value;;
val _to_pmaplist : Netxdr.xdr_value -> pmaplist;;
val _of_pmaplist : pmaplist -> Netxdr.xdr_value;;
val _xof_pmaplist : Netxdr.ctx -> pmaplist -> Netxdr.xdr_value;;
val _to_pmaplist_p : Netxdr.xdr_value -> pmaplist_p;;
val _of_pmaplist_p : pmaplist_p -> Netxdr.xdr_value;;
val _xof_pmaplist_p : Netxdr.ctx -> pmaplist_p -> Netxdr.xdr_value;;
val _to_call_args : Netxdr.xdr_value -> call_args;;
val _of_call_args : call_args -> Netxdr.xdr_value;;
val _xof_call_args : Netxdr.ctx -> call_args -> Netxdr.xdr_value;;
val _to_call_result : Netxdr.xdr_value -> call_result;;
val _of_call_result : call_result -> Netxdr.xdr_value;;
val _xof_call_result : Netxdr.ctx -> call_result -> Netxdr.xdr_value;;
val _to_uaddr : Netxdr.xdr_value -> uaddr;;
val _of_uaddr : uaddr -> Netxdr.xdr_value;;
val _xof_uaddr : Netxdr.ctx -> uaddr -> Netxdr.xdr_value;;
val _to_rpcb : Netxdr.xdr_value -> rpcb;;
val _of_rpcb : rpcb -> Netxdr.xdr_value;;
val _xof_rpcb : Netxdr.ctx -> rpcb -> Netxdr.xdr_value;;
val _to_rp__list : Netxdr.xdr_value -> rp__list;;
val _of_rp__list : rp__list -> Netxdr.xdr_value;;
val _xof_rp__list : Netxdr.ctx -> rp__list -> Netxdr.xdr_value;;
val _to_rpcblist_ptr : Netxdr.xdr_value -> rpcblist_ptr;;
val _of_rpcblist_ptr : rpcblist_ptr -> Netxdr.xdr_value;;
val _xof_rpcblist_ptr : Netxdr.ctx -> rpcblist_ptr -> Netxdr.xdr_value;;
val _to_rpcb_rmtcallargs : Netxdr.xdr_value -> rpcb_rmtcallargs;;
val _of_rpcb_rmtcallargs : rpcb_rmtcallargs -> Netxdr.xdr_value;;
val _xof_rpcb_rmtcallargs : Netxdr.ctx -> rpcb_rmtcallargs -> Netxdr.xdr_value;;
val _to_rpcb_rmtcallres : Netxdr.xdr_value -> rpcb_rmtcallres;;
val _of_rpcb_rmtcallres : rpcb_rmtcallres -> Netxdr.xdr_value;;
val _xof_rpcb_rmtcallres : Netxdr.ctx -> rpcb_rmtcallres -> Netxdr.xdr_value;;
val _to_rpcb_entry : Netxdr.xdr_value -> rpcb_entry;;
val _of_rpcb_entry : rpcb_entry -> Netxdr.xdr_value;;
val _xof_rpcb_entry : Netxdr.ctx -> rpcb_entry -> Netxdr.xdr_value;;
val _to_rpcb_entry_list : Netxdr.xdr_value -> rpcb_entry_list;;
val _of_rpcb_entry_list : rpcb_entry_list -> Netxdr.xdr_value;;
val _xof_rpcb_entry_list : Netxdr.ctx -> rpcb_entry_list -> Netxdr.xdr_value;;
val _to_rpcb_entry_list_ptr : Netxdr.xdr_value -> rpcb_entry_list_ptr;;
val _of_rpcb_entry_list_ptr : rpcb_entry_list_ptr -> Netxdr.xdr_value;;
val _xof_rpcb_entry_list_ptr : Netxdr.ctx -> rpcb_entry_list_ptr -> Netxdr.xdr_value;;
val _to_rpcbs_addrlist : Netxdr.xdr_value -> rpcbs_addrlist;;
val _of_rpcbs_addrlist : rpcbs_addrlist -> Netxdr.xdr_value;;
val _xof_rpcbs_addrlist : Netxdr.ctx -> rpcbs_addrlist -> Netxdr.xdr_value;;
val _to_rpcbs_rmtcalllist : Netxdr.xdr_value -> rpcbs_rmtcalllist;;
val _of_rpcbs_rmtcalllist : rpcbs_rmtcalllist -> Netxdr.xdr_value;;
val _xof_rpcbs_rmtcalllist : Netxdr.ctx -> rpcbs_rmtcalllist -> Netxdr.xdr_value;;
val _to_rpcbs_proc : Netxdr.xdr_value -> rpcbs_proc;;
val _of_rpcbs_proc : rpcbs_proc -> Netxdr.xdr_value;;
val _xof_rpcbs_proc : Netxdr.ctx -> rpcbs_proc -> Netxdr.xdr_value;;
val _to_rpcbs_addrlist_ptr : Netxdr.xdr_value -> rpcbs_addrlist_ptr;;
val _of_rpcbs_addrlist_ptr : rpcbs_addrlist_ptr -> Netxdr.xdr_value;;
val _xof_rpcbs_addrlist_ptr : Netxdr.ctx -> rpcbs_addrlist_ptr -> Netxdr.xdr_value;;
val _to_rpcbs_rmtcalllist_ptr : Netxdr.xdr_value -> rpcbs_rmtcalllist_ptr;;
val _of_rpcbs_rmtcalllist_ptr : rpcbs_rmtcalllist_ptr -> Netxdr.xdr_value;;
val _xof_rpcbs_rmtcalllist_ptr : Netxdr.ctx -> rpcbs_rmtcalllist_ptr -> Netxdr.xdr_value;;
val _to_rpcb_stat : Netxdr.xdr_value -> rpcb_stat;;
val _of_rpcb_stat : rpcb_stat -> Netxdr.xdr_value;;
val _xof_rpcb_stat : Netxdr.ctx -> rpcb_stat -> Netxdr.xdr_value;;
val _to_rpcb_stat_byvers : Netxdr.xdr_value -> rpcb_stat_byvers;;
val _of_rpcb_stat_byvers : rpcb_stat_byvers -> Netxdr.xdr_value;;
val _xof_rpcb_stat_byvers : Netxdr.ctx -> rpcb_stat_byvers -> Netxdr.xdr_value;;
val _to_netbuf : Netxdr.xdr_value -> netbuf;;
val _of_netbuf : netbuf -> Netxdr.xdr_value;;
val _xof_netbuf : Netxdr.ctx -> netbuf -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_null'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_null'arg;;
val _of_PMAP'V2'pmapproc_null'arg : t_PMAP'V2'pmapproc_null'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_null'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_null'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_null'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_null'res;;
val _of_PMAP'V2'pmapproc_null'res : t_PMAP'V2'pmapproc_null'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_null'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_null'res -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_set'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_set'arg;;
val _of_PMAP'V2'pmapproc_set'arg : t_PMAP'V2'pmapproc_set'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_set'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_set'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_set'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_set'res;;
val _of_PMAP'V2'pmapproc_set'res : t_PMAP'V2'pmapproc_set'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_set'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_set'res -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_unset'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_unset'arg;;
val _of_PMAP'V2'pmapproc_unset'arg : t_PMAP'V2'pmapproc_unset'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_unset'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_unset'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_unset'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_unset'res;;
val _of_PMAP'V2'pmapproc_unset'res : t_PMAP'V2'pmapproc_unset'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_unset'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_unset'res -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_getport'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_getport'arg;;
val _of_PMAP'V2'pmapproc_getport'arg : t_PMAP'V2'pmapproc_getport'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_getport'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_getport'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_getport'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_getport'res;;
val _of_PMAP'V2'pmapproc_getport'res : t_PMAP'V2'pmapproc_getport'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_getport'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_getport'res -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_dump'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_dump'arg;;
val _of_PMAP'V2'pmapproc_dump'arg : t_PMAP'V2'pmapproc_dump'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_dump'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_dump'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_dump'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_dump'res;;
val _of_PMAP'V2'pmapproc_dump'res : t_PMAP'V2'pmapproc_dump'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_dump'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_dump'res -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_callit'arg : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_callit'arg;;
val _of_PMAP'V2'pmapproc_callit'arg : t_PMAP'V2'pmapproc_callit'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_callit'arg : Netxdr.ctx -> t_PMAP'V2'pmapproc_callit'arg -> Netxdr.xdr_value;;
val _to_PMAP'V2'pmapproc_callit'res : Netxdr.xdr_value -> t_PMAP'V2'pmapproc_callit'res;;
val _of_PMAP'V2'pmapproc_callit'res : t_PMAP'V2'pmapproc_callit'res -> Netxdr.xdr_value;;
val _xof_PMAP'V2'pmapproc_callit'res : Netxdr.ctx -> t_PMAP'V2'pmapproc_callit'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_null'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_null'arg;;
val _of_PMAP'V3'rpcbproc_null'arg : t_PMAP'V3'rpcbproc_null'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_null'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_null'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_null'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_null'res;;
val _of_PMAP'V3'rpcbproc_null'res : t_PMAP'V3'rpcbproc_null'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_null'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_null'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_set'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_set'arg;;
val _of_PMAP'V3'rpcbproc_set'arg : t_PMAP'V3'rpcbproc_set'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_set'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_set'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_set'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_set'res;;
val _of_PMAP'V3'rpcbproc_set'res : t_PMAP'V3'rpcbproc_set'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_set'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_set'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_unset'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_unset'arg;;
val _of_PMAP'V3'rpcbproc_unset'arg : t_PMAP'V3'rpcbproc_unset'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_unset'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_unset'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_unset'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_unset'res;;
val _of_PMAP'V3'rpcbproc_unset'res : t_PMAP'V3'rpcbproc_unset'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_unset'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_unset'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_getaddr'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_getaddr'arg;;
val _of_PMAP'V3'rpcbproc_getaddr'arg : t_PMAP'V3'rpcbproc_getaddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_getaddr'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_getaddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_getaddr'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_getaddr'res;;
val _of_PMAP'V3'rpcbproc_getaddr'res : t_PMAP'V3'rpcbproc_getaddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_getaddr'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_getaddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_dump'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_dump'arg;;
val _of_PMAP'V3'rpcbproc_dump'arg : t_PMAP'V3'rpcbproc_dump'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_dump'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_dump'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_dump'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_dump'res;;
val _of_PMAP'V3'rpcbproc_dump'res : t_PMAP'V3'rpcbproc_dump'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_dump'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_dump'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_callit'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_callit'arg;;
val _of_PMAP'V3'rpcbproc_callit'arg : t_PMAP'V3'rpcbproc_callit'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_callit'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_callit'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_callit'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_callit'res;;
val _of_PMAP'V3'rpcbproc_callit'res : t_PMAP'V3'rpcbproc_callit'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_callit'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_callit'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_gettime'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_gettime'arg;;
val _of_PMAP'V3'rpcbproc_gettime'arg : t_PMAP'V3'rpcbproc_gettime'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_gettime'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_gettime'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_gettime'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_gettime'res;;
val _of_PMAP'V3'rpcbproc_gettime'res : t_PMAP'V3'rpcbproc_gettime'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_gettime'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_gettime'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_uaddr2taddr'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_uaddr2taddr'arg;;
val _of_PMAP'V3'rpcbproc_uaddr2taddr'arg : t_PMAP'V3'rpcbproc_uaddr2taddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_uaddr2taddr'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_uaddr2taddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_uaddr2taddr'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_uaddr2taddr'res;;
val _of_PMAP'V3'rpcbproc_uaddr2taddr'res : t_PMAP'V3'rpcbproc_uaddr2taddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_uaddr2taddr'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_uaddr2taddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_taddr2uaddr'arg : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_taddr2uaddr'arg;;
val _of_PMAP'V3'rpcbproc_taddr2uaddr'arg : t_PMAP'V3'rpcbproc_taddr2uaddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_taddr2uaddr'arg : Netxdr.ctx -> t_PMAP'V3'rpcbproc_taddr2uaddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V3'rpcbproc_taddr2uaddr'res : Netxdr.xdr_value -> t_PMAP'V3'rpcbproc_taddr2uaddr'res;;
val _of_PMAP'V3'rpcbproc_taddr2uaddr'res : t_PMAP'V3'rpcbproc_taddr2uaddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V3'rpcbproc_taddr2uaddr'res : Netxdr.ctx -> t_PMAP'V3'rpcbproc_taddr2uaddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_null'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_null'arg;;
val _of_PMAP'V4'rpcbproc_null'arg : t_PMAP'V4'rpcbproc_null'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_null'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_null'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_null'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_null'res;;
val _of_PMAP'V4'rpcbproc_null'res : t_PMAP'V4'rpcbproc_null'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_null'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_null'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_set'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_set'arg;;
val _of_PMAP'V4'rpcbproc_set'arg : t_PMAP'V4'rpcbproc_set'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_set'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_set'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_set'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_set'res;;
val _of_PMAP'V4'rpcbproc_set'res : t_PMAP'V4'rpcbproc_set'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_set'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_set'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_unset'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_unset'arg;;
val _of_PMAP'V4'rpcbproc_unset'arg : t_PMAP'V4'rpcbproc_unset'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_unset'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_unset'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_unset'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_unset'res;;
val _of_PMAP'V4'rpcbproc_unset'res : t_PMAP'V4'rpcbproc_unset'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_unset'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_unset'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getaddr'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getaddr'arg;;
val _of_PMAP'V4'rpcbproc_getaddr'arg : t_PMAP'V4'rpcbproc_getaddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getaddr'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getaddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getaddr'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getaddr'res;;
val _of_PMAP'V4'rpcbproc_getaddr'res : t_PMAP'V4'rpcbproc_getaddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getaddr'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getaddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_dump'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_dump'arg;;
val _of_PMAP'V4'rpcbproc_dump'arg : t_PMAP'V4'rpcbproc_dump'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_dump'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_dump'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_dump'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_dump'res;;
val _of_PMAP'V4'rpcbproc_dump'res : t_PMAP'V4'rpcbproc_dump'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_dump'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_dump'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_bcast'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_bcast'arg;;
val _of_PMAP'V4'rpcbproc_bcast'arg : t_PMAP'V4'rpcbproc_bcast'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_bcast'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_bcast'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_bcast'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_bcast'res;;
val _of_PMAP'V4'rpcbproc_bcast'res : t_PMAP'V4'rpcbproc_bcast'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_bcast'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_bcast'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_gettime'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_gettime'arg;;
val _of_PMAP'V4'rpcbproc_gettime'arg : t_PMAP'V4'rpcbproc_gettime'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_gettime'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_gettime'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_gettime'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_gettime'res;;
val _of_PMAP'V4'rpcbproc_gettime'res : t_PMAP'V4'rpcbproc_gettime'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_gettime'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_gettime'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_uaddr2taddr'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_uaddr2taddr'arg;;
val _of_PMAP'V4'rpcbproc_uaddr2taddr'arg : t_PMAP'V4'rpcbproc_uaddr2taddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_uaddr2taddr'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_uaddr2taddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_uaddr2taddr'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_uaddr2taddr'res;;
val _of_PMAP'V4'rpcbproc_uaddr2taddr'res : t_PMAP'V4'rpcbproc_uaddr2taddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_uaddr2taddr'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_uaddr2taddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_taddr2uaddr'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_taddr2uaddr'arg;;
val _of_PMAP'V4'rpcbproc_taddr2uaddr'arg : t_PMAP'V4'rpcbproc_taddr2uaddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_taddr2uaddr'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_taddr2uaddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_taddr2uaddr'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_taddr2uaddr'res;;
val _of_PMAP'V4'rpcbproc_taddr2uaddr'res : t_PMAP'V4'rpcbproc_taddr2uaddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_taddr2uaddr'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_taddr2uaddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getversaddr'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getversaddr'arg;;
val _of_PMAP'V4'rpcbproc_getversaddr'arg : t_PMAP'V4'rpcbproc_getversaddr'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getversaddr'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getversaddr'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getversaddr'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getversaddr'res;;
val _of_PMAP'V4'rpcbproc_getversaddr'res : t_PMAP'V4'rpcbproc_getversaddr'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getversaddr'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getversaddr'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_indirect'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_indirect'arg;;
val _of_PMAP'V4'rpcbproc_indirect'arg : t_PMAP'V4'rpcbproc_indirect'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_indirect'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_indirect'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_indirect'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_indirect'res;;
val _of_PMAP'V4'rpcbproc_indirect'res : t_PMAP'V4'rpcbproc_indirect'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_indirect'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_indirect'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getaddrlist'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getaddrlist'arg;;
val _of_PMAP'V4'rpcbproc_getaddrlist'arg : t_PMAP'V4'rpcbproc_getaddrlist'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getaddrlist'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getaddrlist'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getaddrlist'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getaddrlist'res;;
val _of_PMAP'V4'rpcbproc_getaddrlist'res : t_PMAP'V4'rpcbproc_getaddrlist'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getaddrlist'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getaddrlist'res -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getstat'arg : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getstat'arg;;
val _of_PMAP'V4'rpcbproc_getstat'arg : t_PMAP'V4'rpcbproc_getstat'arg -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getstat'arg : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getstat'arg -> Netxdr.xdr_value;;
val _to_PMAP'V4'rpcbproc_getstat'res : Netxdr.xdr_value -> t_PMAP'V4'rpcbproc_getstat'res;;
val _of_PMAP'V4'rpcbproc_getstat'res : t_PMAP'V4'rpcbproc_getstat'res -> Netxdr.xdr_value;;
val _xof_PMAP'V4'rpcbproc_getstat'res : Netxdr.ctx -> t_PMAP'V4'rpcbproc_getstat'res -> Netxdr.xdr_value;;

(* XDR definitions *)

val xdrt_mapping : Netxdr.xdr_type_term;;
val xdrt_pmaplist : Netxdr.xdr_type_term;;
val xdrt_pmaplist_p : Netxdr.xdr_type_term;;
val xdrt_call_args : Netxdr.xdr_type_term;;
val xdrt_call_result : Netxdr.xdr_type_term;;
val xdrt_uaddr : Netxdr.xdr_type_term;;
val xdrt_rpcb : Netxdr.xdr_type_term;;
val xdrt_rp__list : Netxdr.xdr_type_term;;
val xdrt_rpcblist_ptr : Netxdr.xdr_type_term;;
val xdrt_rpcb_rmtcallargs : Netxdr.xdr_type_term;;
val xdrt_rpcb_rmtcallres : Netxdr.xdr_type_term;;
val xdrt_rpcb_entry : Netxdr.xdr_type_term;;
val xdrt_rpcb_entry_list : Netxdr.xdr_type_term;;
val xdrt_rpcb_entry_list_ptr : Netxdr.xdr_type_term;;
val xdrt_rpcbs_addrlist : Netxdr.xdr_type_term;;
val xdrt_rpcbs_rmtcalllist : Netxdr.xdr_type_term;;
val xdrt_rpcbs_proc : Netxdr.xdr_type_term;;
val xdrt_rpcbs_addrlist_ptr : Netxdr.xdr_type_term;;
val xdrt_rpcbs_rmtcalllist_ptr : Netxdr.xdr_type_term;;
val xdrt_rpcb_stat : Netxdr.xdr_type_term;;
val xdrt_rpcb_stat_byvers : Netxdr.xdr_type_term;;
val xdrt_netbuf : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_null'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_null'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_set'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_set'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_unset'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_unset'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_getport'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_getport'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_dump'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_dump'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_callit'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V2'pmapproc_callit'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_null'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_null'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_set'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_set'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_unset'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_unset'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_getaddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_getaddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_dump'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_dump'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_callit'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_callit'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_gettime'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_gettime'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_uaddr2taddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_uaddr2taddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_taddr2uaddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V3'rpcbproc_taddr2uaddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_null'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_null'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_set'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_set'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_unset'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_unset'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getaddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getaddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_dump'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_dump'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_bcast'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_bcast'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_gettime'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_gettime'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_uaddr2taddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_uaddr2taddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_taddr2uaddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_taddr2uaddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getversaddr'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getversaddr'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_indirect'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_indirect'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getaddrlist'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getaddrlist'res : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getstat'arg : Netxdr.xdr_type_term;;
val xdrt_PMAP'V4'rpcbproc_getstat'res : Netxdr.xdr_type_term;;

(* Program definitions *)

val program_PMAP'V2 : Rpc_program.t;;
val program_PMAP'V3 : Rpc_program.t;;
val program_PMAP'V4 : Rpc_program.t;;

